### ISSUE TITLE
Slow release execution time with NDEBUG

### ISSUE THREAD

**Issue by MPJansen** [flexible-collision-library/fcl#168]
When playing with the new templated version of fcl I was stumped about the slow execution time of the tests compared to reported performance. 
This is on Windows 10 x64 Visual Studio 2015 release build for x86.
Furthermore, the debug build tests seemed to execute a lot faster (factor 3) than the release builds.

I found that CMAKE sets the NDEBUG pre-processor flags for non debug builds, removing the flag  causes tremendous speedup. I know too little of these options to know if this is a solution or not.

Kind regards.

**Comment by MPJansen** [comment]
I just realised, the amount of test executions is not the same for debug and ndebug.
So perhaps I should close this issue

Kind regards

**Comment by jslee02** [comment]
The size of tests for debug mode are adjusted because of the slow performance of Eigen in debug mode. It's known that Eigen is slow in debug mode due to lots of alignment checkings). FCL couldn't pass the CI tests without the test size adjustment (it exceeds 10 min limitations without any outputs).

Regarding the performance in release mode: After migration to Eigen for math operations, the overall performance is not great as much as FCL 0.5 yet. There are more rooms for improvements by taking the advantage of Eigen features. I'm working on this.

**Comment by chhtz** [comment]
The reason Eigen is slow in debug mode is less caused by alignment checks, but by the high amount of (not inlined) expression template code. Even compiling with `-O1` (on gcc or clang) usually gives reasonable execution times.

**Comment by jslee02** [comment]
Good to know! Thanks for the correction. 

Is it considerable to use `-O1` for debug building then?

**Comment by chhtz** [comment]
I would definitely add `-O1` if you want usuable execution speeds. It does of course slightly slightly complicate debugging code (but not as bad as `-O2` or `-O3`).

**Comment by MPJansen** [comment]
Interesting,

I'll see if I can profile fcl a bit to see what's the bottleneck. Firstly I was just confused by the difference between debug and not, but I jumped the gun a bit..

Shall I close this?

grts
