### ISSUE TITLE
Failure in building mesh using fcl::BVHModel< fcl::OBB >::addVectex

### ISSUE THREAD

**Issue by florent-lamiraux** [flexible-collision-library/fcl#20]
I try to build a mesh using the following naive procedure
```
boost::shared_ptr <fcl::BVHModel< fcl::OBB > mesh
(new (fcl::BVHModel< fcl::OBB >));
mesh->beginModel ();
// Loop over a previously filled vector of vectices
for (std::size_type  i = 0; i<vertices.size (); ++i)
  mesh->addVertex (vertices [i]);
// Loop over a previously filled vector of triangles
for (std::size_type  i = 0; i<triangles.size (); ++i)
  mesh->addVertex (triangles [i]);
mesh->endModel ();
```
This does not works since method beginModel sets ```build_state``` member of mesh
to ```BVH_BUILD_STATE_BEGUN``` and method ```addVertex``` expects BVH_BUILD_STATE_UPDATE_BEGUN as value for ```build_state```.

I noticed that addVertex is not used in tests. Did I do something wrong ?

**Comment by jslee02** [comment]
It seems it's a typo to me so `addVertex` should expect `BVH_BUILD_STATE_BEGUN`.

One caveat is that `addTriangle` must be used to add triangles to the BVH model instead of `addVertex` under the current API. It seems `addVertex` is for point cloud models, and [FCL doesn't expect the case of mixed use of `addVertex` and `addTriangle`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/BVH/BVH_model.h#L60).
