### ISSUE TITLE
Inverting Transform<S> without extra work

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [flexible-collision-library/fcl#317]
The `fcl::Transform` type is an [alias for the `Eigen::Transform` with the `Eigen::AffineCompact`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/common/types.h#L89). When calling `inverse()` on that method, the `Affine` designation requires that the `linear()` portion have its inverse [computed explicitly](https://bitbucket.org/eigen/eigen/src/0b88199f5b4a7cf10f19855dec234fb321220007/Eigen/src/Geometry/Transform.h?at=3.0&fileviewer=file-view-default#Transform.h-1124).  If the transform generally represents a "rigid" transformation (i.e., rotation and translation), then the inverse of the linear portion should simply be its transpose. This code path is only available if the Transform "mode" is declared to be "Isometry". The problem is we do *a lot* of transforming geometries into other frames by computing inverses.

The `inverse()` method can take a "hint" indicating what *should* be done. I.e., if I know that my transform is strictly a rotation and translation, I can force it to transpose the rotation by passing in `Eigen::Isometry`. It seems it would be good to empower users to do this, based on their certain knowledge.

I'd propose we add a common `fast_inverse` method that essentially does this (and is documented in its assumptions). Something along the lines of:

```c++
/// Creates the inverse of the transform by assuming that the transform is strictly a
/// rotation and translation. The inverse of the rotation is strictly its transpose. This
/// should only be called if the given transform is properly a concatenation of *only*
/// rotation and translation. 
/// @param X_AB   A transform mapping the relationship between frame A and B.
/// @retval X_BA   The inverse of X_AB⁻¹ = X_BA such that X_BA * X_AB = I.
template <typename S>
Transform<S> fast_inverse(const Transform<S>& X_AB) {
   return X_AB.inverse(Eigen::Isometry);
}
```

Issues to consider
  - Users can really screw themselves if they are incorrect in their belief that their X_AB's linear() component is an orthonormal matrix. Computing the inverse generally will give us the most consistent guarantee that `X_BA * X_AB = I`
  - We should also provide some independent test/measure that suggests to them that their transform is "good enough" to be used in a fast transform.

Thoughts?

**Comment by amcastro-tri** [comment]
why not changing the using to `Eigen::Transform<Scalar, 3, Eigen::Isometry>;`? any reason to have the `AffineCompact`? is that even used anywhere?

**Comment by sherm1** [comment]
I wonder if it would make more sense to convert FCL to use Isometry exclusively for its transforms. Does it every use them for anything but rigid transformations?

**Comment by sherm1** [comment]
(Oh, didn't see @amcastro-tri's comment -- yes, :+1:)

**Comment by jslee02** [comment]
When I write this type alias, I considered following aspects ([similar consideration in DART](https://github.com/dartsim/dart/issues/767#issue-173627954)):

- `AffineCompact` uses lesser memory than `Isometry` because it doesn't explicitly store the 4th row, which is always `[0 0 0 1]`.
- The rigid transformation is still available by `X_AB.inverse(Eigen::Isometry)` anyway. Also, this is can be specified in compile time so there would be no runtime overhead.

However, I don't know, at least for now, how the less memory consumption of using `AffineCompact` impacts the performance. In addition, I can see that it could easily happen to the user to use unnecessarily inefficient inversion by default. Based on these, I'm totally open to switching to `Isometry`.

**Comment by sherm1** [comment]
(Hi, JS!) We used Isometry exclusively in Drake for a long time. I don't think the extra memory mattered since we don't typically store a large number of transforms, and Eigen is good about ignoring the last row in Isometry operations.

(That said, we are actually switching to a custom RigidTransform class mainly to provide a better API and considerably better error detection and reporting. But I think the Isometry would be an improvement in FCL if it has the right functionality, and especially if we can call it `fcl::Transform`, rather that "Isometry" which basically confuses everyone who encounters it!)

**Comment by amcastro-tri** [comment]
So if we re-define the `fcl::Transform` alias, do we get CI hell or it does fix our problems? 
anybody volunteering to give that a try?

**Comment by SeanCurtis-TRI** [comment]
I'll try changing to Isometry and see what it does to the tests. If it's easy, then we can go with it. If causes lots to blow up, we'll have to evaluate more carefully.

One thing I noted is that in cases where I ran head first into it, the `inverse()` computed was *not* the transpose, which suggests there's an issue on how orthonormal ostensibly orthonormal matrices actually are.
