### ISSUE TITLE
Help understanding the convex shape type?

### ISSUE THREAD

**Issue by Levi-Armstrong** [flexible-collision-library/fcl#320]
I needing help understanding what is the correct format of the data when using the convex shape type.

It requires:
- plane normals
- plane distances 
- number of planes
- points
- number of points 
- polygons

I have a few questions.

1. Is there documentation or examples related to this shape type?
1. Should the plane normals point inward or outward?
1. Does having duplicate points cause issues?
1. Does the order(reversed) of the points defining the polygon matter?

**Comment by SeanCurtis-TRI** [comment]
These are good questions and presage my own archaeology into that domain. Given issues you've created since this issue (#322) it seems you have some answers to these questions. It would be grand if you could capture the answers you've discovered. 

Ideally, it would be grand if you could doxygen it up and submit a PR. Failing that, documenting the answers here so that someone else can PR it into doxygen would be an acceptable alternative.

In the name of completeness (and hoping this doesn't unintentionally inspire to "just wait"), when I get to really exercising the convex geometry type myself, I'll be adding this documentation if it's not already there. I'd really appreciate being able to springboard off of your fine work.

**Comment by Levi-Armstrong** [comment]
Sure, 

I will create a PR to document along with tests related to convex shapes once issue #322 is resolved. I currently have several tests but they depend on ROS packages for importing the stl. Does FCL contain any utilities for reading mesh files, if not I will just update the test to create a sphere mesh opposed to importing from file?

- Is there documentation or examples related to this shape type?
  - I will document the existing API with what I know works.
- Should the plane normals point inward or outward?
  - From my limited testing I would say the normals should be pointing outward.
- Does having duplicate points cause issues?
  - This does not seem to be an issue. I think its just important that plane normals and triangle vertex ordering be correct.
- Does the order(reversed) of the points defining the polygon matter?
  - I missed this in the API but it does state that the order should be counter clockwise.

**Comment by SeanCurtis-TRI** [comment]
In cleaning up a stale PR I ended up doing *some* of this. Take a look at #325.

**Comment by SeanCurtis-TRI** [comment]
I'm going to close this based on the update in #325. If there are outstanding issues, we can open a new issue.
