### ISSUE TITLE
Can FCL be linked using add_subdirectory in CMake?

### ISSUE THREAD

**Issue by aWeinzierl** [flexible-collision-library/fcl#359]
Hi, 

I have a question:

I use CMake and would like to use FCL without having to install it somewhere and then point there when compiling.

Thus, I'd like to just put it into my source folder and link to it using add_subdirectory(dirToFCL) and target_link_librararies(mytarget <fcl>).

Is this possible? If yes, how?

**Comment by traversaro** [comment]
Hi @aWeinzierl, I just did a small test about this using the latest fcl master and CMake's [FetchContent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html), and it seems to be working fine:
~~~cmake
cmake_minimum_required(VERSION 3.11)

project(fcl-test)

include(FetchContent)
FetchContent_Declare(fcl
                     GIT_REPOSITORY https://github.com/flexible-collision-library/fcl.git)

FetchContent_GetProperties(fcl)
if(NOT fcl_POPULATED)
  FetchContent_Populate(fcl)
  add_subdirectory(${fcl_SOURCE_DIR} ${fcl_BINARY_DIR})
endif()

add_executable(main main.cpp)
target_link_libraries(main fcl)

install(TARGETS main DESTINATION bin)
~~~
If you add with `add_subdirectory` a directory containing fcl, it should be sufficient to link the `fcl` target to link to fcl. Note that by using fcl in this way, you will also install it when you install your project, so pay attention for possible collision with an fcl already installed in the same prefix.

**Comment by traversaro** [comment]
I see. I did a quick test and apparently that is not supported by FCL out of the box, due to how ccd is searched. However with this patch: https://github.com/traversaro/fcl/commit/d8554a9f9f135a3bcf52ef2eaf4e951ffb6c58ee , I was able to successfully compile the following project:
~~~cmake
cmake_minimum_required(VERSION 3.11)

project(fcl-test)

include(FetchContent)

# Avoid that ccd pollutes the CMake build with test targets
set(CCD_HIDE_ALL_SYMBOLS ON)
FetchContent_Declare(libccd
                     GIT_REPOSITORY https://github.com/danfis/libccd)
FetchContent_GetProperties(libccd)
if(NOT libccd_POPULATED)
  FetchContent_Populate(libccd)
  add_subdirectory(${libccd_SOURCE_DIR} ${libccd_BINARY_DIR})
endif()

FetchContent_Declare(fcl
                     GIT_REPOSITORY https://github.com/flexible-collision-library/fcl.git)
FetchContent_GetProperties(fcl)
if(NOT fcl_POPULATED)
  FetchContent_Populate(fcl)
  add_subdirectory(${fcl_SOURCE_DIR} ${fcl_BINARY_DIR})
endif()

add_executable(main main.cpp)
target_link_libraries(main fcl)

install(TARGETS main DESTINATION bin)
~~~

**Comment by aWeinzierl** [comment]
Seems to work for me. 
Thank you very much for the fast and elaborate help.

You've got another user for your library (which btw has a nice API) ;-)
