### ISSUE TITLE
test_fcl_distance NearestPointFromDegenerateSimplex fails on macOS

### ISSUE THREAD

**Issue by jamiesnape** [flexible-collision-library/fcl#361]
According to CI. Probably due to a change in the version of a Homebrew dependency than a code change.

```
Test #13: test_fcl_distance ...............................***Failed    3.26 sec
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from FCL_DISTANCE
[ RUN      ] FCL_DISTANCE.mesh_distance
distance timing: 0.054579 sec
collision timing: 0.036614 sec
[       OK ] FCL_DISTANCE.mesh_distance (3253 ms)
[ RUN      ] FCL_DISTANCE.NearestPointFromDegenerateSimplex
/Users/user/fcl/test/test_fcl_distance.cpp:363: Failure
The difference between expected_dist and result.min_distance is 2.3454265710154409e-07, which exceeds constants<ccd_real_t>::eps_34(), where
expected_dist evaluates to 0.053516322172152138,
result.min_distance evaluates to 0.053516087629495036, and
constants<ccd_real_t>::eps_34() evaluates to 1.8189894035458565e-12.
[  FAILED  ] FCL_DISTANCE.NearestPointFromDegenerateSimplex (0 ms)
[----------] 2 tests from FCL_DISTANCE (3253 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (3253 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FCL_DISTANCE.NearestPointFromDegenerateSimplex

 1 FAILED TEST
```

**Comment by jamiesnape** [comment]
(Will post more details when I have a chance to do a local build.)

**Comment by SeanCurtis-TRI** [comment]
Further thoughts/notes/observations:

Starting [Jan 16, 2019](https://travis-ci.org/flexible-collision-library/fcl/builds/480449098), we've introduced a new, persistent failure in the mac CI builds. Specificaly:

test_fcl_distance.cpp, NearestPointFromDegenerateSimplex(). This test arose from a bug reported in #293 and fixed by #296. However, the test is documented as having some very specific requirements which may or may not be met. 

It's also not clear if something changed in travis.ci mac configuration between the last successful run on [Dec. 12, 2018](https://travis-ci.org/flexible-collision-library/fcl/builds/469727474) and the failure linked above. Certainly, the change on Jan. 16 seems wholly unrelated.

**Comment by jamiesnape** [comment]
I would guess the latest version of `libccd` is to blame. Looks like CI uses Homebrew for that dependency and there was a version bump December 23rd (https://github.com/Homebrew/homebrew-core/commit/fd3ddd77143563751d6e0f83e8d51a5f97a95b53) diff (https://github.com/danfis/libccd/compare/v2.0...danfis:v2.1). Same issue as https://github.com/RobotLocomotion/drake/issues/10577, perhaps even.

**Comment by SeanCurtis-TRI** [comment]
I think you're right. I'm going to investigate the three commits and figure out the implication. The nice thing is that I can advance my libccd to the same version and should be able to reproduce the errors locally (finally!)
