### ISSUE TITLE
Deformable Mesh Continuous Collision Detection

### ISSUE THREAD

**Issue by Mx7f** [flexible-collision-library/fcl#412]
In the original FCL paper (http://gamma.cs.unc.edu/FCL/fcl_docs/webpage/pdfs/fcl_icra2012.pdf); Table IV and Figure 5 are dedicated to doing collision detection (and CCD) on deformable meshes from the UNC Dynamic Scene Benchmark (http://gamma.cs.unc.edu/DYNAMICB/).

The datasets are sequences of triangle meshes, where the connectivity is constant, only vertex positions change. The paper implies that FCL keeps track of previous vertex positions, which allows it to do CCD on these deforming meshes. However, the high level API seems to only support a single transform for the entire mesh for continous collision detection, in `continuousCollide()`. Is there some way to do collision detection on deformable models with current FCL (besides breaking meshes into individual triangles, and calculating transforms that warp from one timestep to another, which sounds very slow).

**Comment by SeanCurtis-TRI** [comment]
I haven't played with the CCD in FCL, but I glanced at it after seeing your issue.

As near as I can tell, I don't see support for deformable meshes. The continuous collision detection seems to be about a `Geometry` and a `MotionBase` -- and the motion base seems to consist of "translational", "spline", "screw", and "interpolation" -- all of those seems to consist of computing *transforms* in an interval of an otherwise rigid geometry.

So, if there's deformable geometry lurking in there, it defined my two-minute search. Let's see if anyone with more particular knowledge can weigh in.

**Comment by SeanCurtis-TRI** [comment]
Closing as a conversation that hasn't moved for a while (and doesn't imply an explicit action). Feel free to re-open if some new information comes to light.
