### ISSUE TITLE
Could FCL use full triangular meshes for moving 3D objects rather than convex hull  meshes?

### ISSUE THREAD

**Issue by jclinton830** [flexible-collision-library/fcl#418]
Hi, 

This is more of a question than an issue. I am in the process of building a robotics simulation software. Currently, I perform collision detection and avoidance using the Bullet real time physics library. Bullet requires me to use convex hull mesh representations for the 3D models to perform collision detection. 

Now I would like to have the actual triangular mesh representation of the 3D models and perform collision detection for them. I know in Moveit a similar approach is taken. So I am just wanting some confirmation before I dive deep into the integration of FCL into my software. 

Is this possible with FCL? 

Cheers.

**Comment by SeanCurtis-TRI** [comment]
FCL does support queries on triangular meshes. Like Bullet, it will be slower because it can't use convexity-based algorithms. I have no idea how much slower it is. It will also suffer if you have two meshes whose surfaces don't intersect -- imagine a small ball passing fully into a big ball. I honestly have no idea what is returned in that case; I don't know how much the collision method is dependent on detecting intersecting triangles. I suspect that this collision will be missed.

**Comment by jclinton830** [comment]
Thanks @SeanCurtis-TRI 

Good to know that. I might try the V-HACD to make near representation of my meshes as convex hulls and see whether that increases the performance.
