### ISSUE TITLE
Question about HierarchyTree::bounds

### ISSUE THREAD

**Issue by yuzhangbit** [flexible-collision-library/fcl#421]
When I looked into the implementation of the `HierarchyTree::bounds` at [line 987](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/broadphase/detail/hierarchy_tree-inl.h#L987), 
```c++
template<typename BV>
BV HierarchyTree<BV>::bounds(const NodeVecIterator lbeg, const NodeVecIterator lend)
{
  if(lbeg == lend) return BV();
  BV bv = *lbeg;
  for(NodeVecIterator it = lbeg + 1; it < lend; ++it)
  {
    bv += (*it)->bv;
  }

  return bv;
}
```
I found that `BV bv = *lbeg` is suspicious. Shouldn't it be `BV bv = (*lbeg)->bv`?

**Comment by SeanCurtis-TRI** [comment]
Hi @yuzhangbit. I think your observation is spot on.

At first it looked like a *huge* conundrum. After all, given the change you suggested, how would it even compile? Two options:

1. There is some constructor overload to a BV from a NodeBase<BV> (allowing it to compile).
2. This code is never seen by the compiler.

It appears to be the second case.

There are *two* `bounds()` methods. Both are `private static` members of `HierarchyTree`. *Neither* are ever exercised by `HierarchyTree` (the only class that *can* exercise them). Furthermore, the two overloads of `bounds()` are not expressed in terms of each other.

So, we have several options:

1. Remove these unused functions (although, given their apparent purpose, I'd have to dig through to find which functions are serving this apparently useful purpose).
2. Fix the functions so that they at least work if someone happened to to use them
    - This would entail expressing one overload in terms of the other and
    - putting the method under test.

How did you come across this defect? Do you need these methods? Worth fixing or just killing?

**Comment by yuzhangbit** [comment]
@SeanCurtis-TRI Thanks for your reply.  I think these dead codes should be removed if not used by any other functions.  
This is not the only dead code block I found. See [https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/broadphase/detail/hierarchy_tree-inl.h#L1090](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/broadphase/detail/hierarchy_tree-inl.h#L1090)

```c++
static bool run(
      const HierarchyTree<AABB<S>>& tree,
      typename HierarchyTree<AABB<S>>::NodeType* leaf,
      const AABB<S>& bv_,
      const Vector3<S>& vel,
      S margin)
  {
    AABB<S> bv(bv_);
    if(leaf->bv.contain(bv)) return false;
    Vector3<S> marginv(margin);
    bv.min_ -= marginv;
    bv.max_ += marginv;
    if(vel[0] > 0) bv.max_[0] += vel[0];
    else bv.min_[0] += vel[0];
    if(vel[1] > 0) bv.max_[1] += vel[1];
    else bv.min_[1] += vel[1];
    if(vel[2] > 0) bv.max_[2] += vel[2];
    else bv.min_[2] += vel[2];
    tree.update(leaf, bv);
    return true;
  }
```
The initialization of the `marginv` is clearly not right. It should be `Vector3<S> marginv = Vector3<S>::Constant(margin)`. It is also not called by others.
