### ISSUE TITLE
Documentation on fcl::Contact

### ISSUE THREAD

**Issue by tonydangct** [flexible-collision-library/fcl#426]
Some clear documentation on the ```fcl::Contact struct``` would be useful. Currently the only documentation I found is [here](http://docs.ros.org/fuerte/api/fcl/html/structfcl_1_1Contact.html), but to me some variables still remain unclear. For example, the explanation for ```Vec3f  pos```: "contact position, in world space" still remains quite vague to me.  A collision always happens between 2 bodies with a volume, so how exactly is this collision reduced to a single point in space?

**Comment by SeanCurtis-TRI** [comment]
It's worse than you think. Look at #384. I'm inclined to close this issue in favor of that one. You alright with that?

**Comment by tonydangct** [comment]
Sure, no problem. Thanks for the quick response!

**Comment by SeanCurtis-TRI** [comment]
Also, feel free to comment on that issue if this is an active pain point, or "merely" an annoyance.

Generally, it'll be obnoxious to change because it could potentially break a lot of code. It'll have to change with a major revision. I can imagine that there's code out there that is accommodating the idiosyncracies and if those suddenly disappeared...well, you know.
