### ISSUE TITLE
collide returns false on overlaping concave meshes

### ISSUE THREAD

**Issue by MFridlyand** [flexible-collision-library/fcl#492]
I load two meshes from *.obj files and make BVHModel from them. One mesh is completely inside another, they don't intersect, but overlap. collide call returns zero contacts and distance call returns positive distance. I looked inside code and it looks like it could be reproduced on any noninstersecting overlaping meshes.

[fcl_resources.zip](https://github.com/flexible-collision-library/fcl/files/5158834/fcl_resources.zip)

**Comment by SeanCurtis-TRI** [comment]
That's got to be due to #488. Let me look into it quickly.

**Comment by SeanCurtis-TRI** [comment]
Oops. My bad. I saw "concave" and thought "convex". This is wholly *unrelated* to #488.

The true answer is one that is not going to make you happy. The non-convex meshes *cannot* detect contact if the *surfaces* are not in contact. This is due to the fact that the algorithm being used to detect contact between general meshes makes no assumptions about meshes having an "inside" or an "outside" and therefore only detects contact on the surface. So, the scenario you describe will invariably be missed by FCL. There is no expectation (at least, none that I've heard) that this behavior will change any time in the future.
